# Default environment variable values.
# These values can be overwritten in the following `Makefile.env.local` which is not under version control
# and can be adapted for individual developer requirements.

export SHELL:=/bin/bash
export VENDOR:=codemityio
export DEBUG:=false
